const actionTypes ={
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    REGISTER: 'REGISTER',
    LOGOUT:'LOGOUT',
    GETHOTELS_FAIL: 'GETHOTELS_FAIL',
    GETHOTELS_SUCCESS: 'GETHOTELS_SUCCESS',
    GET_CURRENT:'GET_CURRENT'
}
export default actionTypes;